// Generated by https://quicktype.io

export interface DataResponse {
  status: Status;
  data:   Datum[];
}

export interface Datum {
  id:                      string;
  serial_id:               number;
  symbol:                  string;
  name:                    string;
  slug:                    string;
  contract_addresses:      ContractAddress[] | null;
  _internal_temp_agora_id: string;
  metrics:                 Metrics;
  profile:                 Profile;
}

export interface ContractAddress {
  platform:         string;
  contract_address: string;
}

export interface Metrics {
  market_data:               MarketData;
  marketcap:                 Marketcap;
  supply:                    MetricsSupply;
  blockchain_stats_24_hours: { [key: string]: number | null };
  market_data_liquidity:     MarketDataLiquidity;
  all_time_high:             AllTimeHigh;
  cycle_low:                 CycleLow;
  token_sale_stats:          TokenSaleStats;
  mining_stats:              MiningStats;
  developer_activity:        DeveloperActivity;
  roi_data:                  { [key: string]: number | null };
  roi_by_year:               { [key: string]: number | null };
  risk_metrics:              RiskMetrics;
  misc_data:                 MiscData;
  reddit:                    Reddit;
  on_chain_data:             { [key: string]: number | null };
  exchange_flows:            { [key: string]: number | null };
  miner_flows:               MinerFlows;
  supply_activity:           { [key: string]: number | null };
  supply_distribution:       { [key: string]: number | null };
  alert_messages:            null;
}

export interface AllTimeHigh {
  price:              number;
  at:                 string;
  days_since:         number;
  percent_down:       number;
  breakeven_multiple: number;
}

export interface CycleLow {
  price:      number;
  at:         string;
  percent_up: number;
  days_since: number;
}

export interface DeveloperActivity {
  stars:                       number | null;
  watchers:                    number | null;
  commits_last_3_months:       null;
  commits_last_1_year:         null;
  lines_added_last_3_months:   null;
  lines_added_last_1_year:     null;
  lines_deleted_last_3_months: null;
  lines_deleted_last_1_year:   null;
}

export interface MarketData {
  price_usd:                                   number;
  price_btc:                                   number;
  price_eth:                                   number;
  volume_last_24_hours:                        number;
  real_volume_last_24_hours:                   number;
  volume_last_24_hours_overstatement_multiple: number;
  percent_change_usd_last_1_hour:              number | null;
  percent_change_btc_last_1_hour:              number | null;
  percent_change_eth_last_1_hour:              number | null;
  percent_change_usd_last_24_hours:            number | null;
  percent_change_btc_last_24_hours:            number | null;
  percent_change_eth_last_24_hours:            number | null;
  ohlcv_last_1_hour:                           OhlcvLastHour | null;
  ohlcv_last_24_hour:                          OhlcvLastHour | null;
  last_trade_at:                               string;
}

export interface OhlcvLastHour {
  open:   number;
  high:   number;
  low:    number;
  close:  number;
  volume: number;
}

export interface MarketDataLiquidity {
  clearing_prices_to_sell: null;
  marketcap:               null;
  asset_bid_depth:         null;
  usd_bid_depth:           null;
  updated_at:              string;
}

export interface Marketcap {
  rank:                                  number;
  marketcap_dominance_percent:           number;
  current_marketcap_usd:                 number;
  y_2050_marketcap_usd:                  number | null;
  y_plus10_marketcap_usd:                number | null;
  liquid_marketcap_usd:                  number | null;
  volume_turnover_last_24_hours_percent: number | null;
  realized_marketcap_usd:                number | null;
  outstanding_marketcap_usd:             number | null;
}

export interface MinerFlows {
  supply_1hop_miners_usd:          number | null;
  supply_1hop_miners_native_units: number | null;
  supply_miners_usd:               number | null;
  supply_miners_native_units:      number | null;
}

export interface MiningStats {
  mining_algo:                                     null | string;
  network_hash_rate:                               null | string;
  available_on_nicehash_percent:                   number | null;
  "1_hour_attack_cost":                            null;
  "24_hours_attack_cost":                          null;
  attack_appeal:                                   null;
  hash_rate:                                       number | null;
  hash_rate_30d_average:                           number | null;
  mining_revenue_per_hash_usd:                     number | null;
  mining_revenue_per_hash_native_units:            number | null;
  mining_revenue_per_hash_per_second_usd:          number | null;
  mining_revenue_per_hash_per_second_native_units: number | null;
  mining_revenue_from_fees_percent_last_24_hours:  number | null;
  mining_revenue_native:                           number | null;
  mining_revenue_usd:                              number | null;
  mining_revenue_total:                            number | null;
  average_difficulty:                              number | null;
}

export interface MiscData {
  private_market_price_usd:                number | null;
  vladimir_club_cost:                      null;
  btc_current_normalized_supply_price_usd: null;
  btc_y2050_normalized_supply_price_usd:   null;
  asset_created_at:                        null;
  asset_age_days:                          null;
  categories:                              Category[] | null;
  sectors:                                 string[] | null;
  tags:                                    string[] | null;
}

export enum Category {
  Financial = "Financial",
  Infrastructure = "Infrastructure",
  Payments = "Payments",
}

export interface Reddit {
  active_user_count: number | null;
  subscribers:       number | null;
}

export interface RiskMetrics {
  sharpe_ratios:    SharpeRatios;
  volatility_stats: VolatilityStats;
}

export interface SharpeRatios {
  last_30_days: number | null;
  last_90_days: number | null;
  last_1_year:  number | null;
  last_3_years: number | null;
}

export interface VolatilityStats {
  volatility_last_30_days: number | null;
  volatility_last_90_days: number | null;
  volatility_last_1_year:  number | null;
  volatility_last_3_years: number | null;
}

export interface MetricsSupply {
  y_2050:                   number | null;
  y_plus10:                 number | null;
  liquid:                   number | null;
  circulating:              number;
  y_2050_issued_percent:    number | null;
  annual_inflation_percent: number | null;
  stock_to_flow:            number | null;
  y_plus10_issued_percent:  number | null;
  supply_revived_90d:       number | null;
}

export interface TokenSaleStats {
  sale_proceeds_usd:          null;
  sale_start_date:            null;
  sale_end_date:              null;
  roi_since_sale_usd_percent: null;
  roi_since_sale_btc_percent: null;
  roi_since_sale_eth_percent: null;
}

export interface Profile {
  general:      ProfileGeneral;
  contributors: Ors;
  advisors:     Ors;
  investors:    Ors;
  ecosystem:    Ecosystem;
  economics:    Economics;
  technology:   Technology;
  governance:   Governance;
  metadata:     Metadata;
}

export interface Ors {
  individuals:   Individual[] | null;
  organizations: Organization[] | null;
}

export interface Individual {
  slug:        string;
  first_name:  string;
  last_name:   null | string;
  title:       null | string;
  description: null | string;
  avatar_url:  null | string;
}

export interface Organization {
  slug:        string;
  name:        string;
  logo:        null | string;
  description: null | string;
}

export interface Economics {
  token:                  Token;
  launch:                 Launch;
  consensus_and_emission: ConsensusAndEmission;
  native_treasury:        NativeTreasury;
}

export interface ConsensusAndEmission {
  supply:    ConsensusAndEmissionSupply;
  consensus: Consensus;
}

export interface Consensus {
  consensus_details:              null | string;
  general_consensus_mechanism:    null | string;
  precise_consensus_mechanism:    null | string;
  targeted_block_time:            number | null;
  block_reward:                   number | null;
  mining_algorithm:               null | string;
  next_halving_date:              null | string;
  is_victim_of_51_percent_attack: boolean | null;
}

export interface ConsensusAndEmissionSupply {
  supply_curve_details:  null | string;
  general_emission_type: GeneralEmissionType | null;
  precise_emission_type: null | string;
  is_capped_supply:      boolean | null;
  max_supply:            number | null;
}

export enum GeneralEmissionType {
  BurnMint = "Burn & Mint",
  Deflationary = "Deflationary",
  FixedSupply = "Fixed Supply",
  Inflationary = "Inflationary",
}

export interface Launch {
  general:              LaunchGeneral;
  fundraising:          Fundraising;
  initial_distribution: InitialDistribution;
}

export interface Fundraising {
  sales_rounds:                    SalesRound[] | null;
  sales_documents:                 BlockExplorer[] | null;
  sales_treasury_accounts:         SalesTreasuryAccount[] | null;
  treasury_policies:               any[] | null;
  projected_use_of_sales_proceeds: ProjectedUseOfSalesProceed[] | null;
}

export interface ProjectedUseOfSalesProceed {
  category:             null | string;
  amount_in_percentage: number | null;
}

export interface BlockExplorer {
  name: string;
  link: string;
}

export interface SalesRound {
  title:                             string;
  start_date:                        null | string;
  type:                              string;
  details:                           null | string;
  end_date:                          null | string;
  native_tokens_allocated:           number | null;
  asset_collected:                   null | string;
  price_per_token_in_asset:          number | null;
  equivalent_price_per_token_in_usd: number | null;
  amount_collected_in_asset:         number | null;
  amount_collected_in_usd:           number | null;
  is_kyc_required:                   boolean | null;
  restricted_jurisdictions:          string[] | null;
}

export interface SalesTreasuryAccount {
  account_type: null | string;
  asset_held:   Asset;
  addresses:    BlockExplorer[];
  security:     null;
}

export interface Asset {
  id:   null | string;
  name: null | string;
}

export interface LaunchGeneral {
  launch_style:   null | string;
  launch_details: null | string;
}

export interface InitialDistribution {
  initial_supply:             number | null;
  initial_supply_repartition: InitialSupplyRepartition;
  token_distribution_date:    null | string;
  genesis_block_date:         null | string;
}

export interface InitialSupplyRepartition {
  allocated_to_investors_percentage:                    number | null;
  allocated_to_organization_or_founders_percentage:     number | null;
  allocated_to_premined_rewards_or_airdrops_percentage: number | null;
}

export interface NativeTreasury {
  accounts:               any[] | null;
  treasury_usage_details: null;
}

export interface Token {
  token_name:          null | string;
  token_type:          TokenType | null;
  token_address:       null | string;
  block_explorers:     BlockExplorer[] | null;
  multitoken:          any[] | null;
  token_usage:         null | string;
  token_usage_details: null | string;
}

export enum TokenType {
  ERC20OmniTRC20 = "ERC-20, Omni, TRC-20",
  Erc20 = "ERC-20",
  Native = "Native",
  NativeERC20 = "Native, ERC-20",
}

export interface Ecosystem {
  assets:        Asset[] | null;
  organizations: Organization[] | null;
}

export interface ProfileGeneral {
  overview:   GeneralOverview;
  background: Background;
  roadmap:    Roadmap[] | null;
  regulation: Regulation;
}

export interface Background {
  background_details:    null | string;
  issuing_organizations: Organization[] | null;
}

export interface GeneralOverview {
  is_verified:     boolean | null;
  tagline:         null | string;
  category:        Category | null;
  sector:          null | string;
  tags:            null | string;
  project_details: null | string;
  official_links:  BlockExplorer[] | null;
}

export interface Regulation {
  regulatory_details: null | string;
  sfar_score:         number | null;
  sfar_summary:       null | string;
}

export interface Roadmap {
  title:   string;
  date:    null | string;
  type:    null | string;
  details: null | string;
}

export interface Governance {
  governance_details: null | string;
  onchain_governance: OnchainGovernance;
  grants:             Grant[] | null;
}

export interface Grant {
  funding_organizations: null;
  grant_program_details: string;
}

export interface OnchainGovernance {
  onchain_governance_type:    null | string;
  onchain_governance_details: null | string;
  is_treasury_decentralized:  boolean | null;
}

export interface Metadata {
  updated_at: string;
}

export interface Technology {
  overview: TechnologyOverview;
  security: Security;
}

export interface TechnologyOverview {
  technology_details:  null | string;
  client_repositories: ClientRepository[] | null;
}

export interface ClientRepository {
  name:         string;
  link:         string;
  license_type: null | string;
}

export interface Security {
  audits:                             Roadmap[] | null;
  known_exploits_and_vulnerabilities: Roadmap[] | null;
}

export interface Status {
  elapsed:   number;
  timestamp: string;
}
